apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platform-governance-service.fullname" . }}-config
  labels:
    {{- include "platform-governance-service.labels" . | nindent 4 }}
data:
  PORT: "4002"
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
