import { z } from 'zod';

export const candidateSchema = z.object({
  name: z.string().nullable().optional().default(null),
  email: z.string().nullable().optional().default(null),
  phone: z.string().nullable().optional().default(null),
  skills: z.union([z.string(), z.array(z.string())]).nullable().optional().default(null),
  primary_skills: z.string().nullable().optional().default(null),
  secondary_skills: z.string().nullable().optional().default(null),
  years_of_experience: z.string().nullable().optional().default(null),
  current_location: z.string().nullable().optional().default(null),
  preferred_location: z.string().nullable().optional().default(null),
  current_company: z.string().nullable().optional().default(null),
  previous_companies: z.array(z.string()).nullable().optional().default(null),
  current_job_title: z.string().nullable().optional().default(null),
  industry_domain: z.string().nullable().optional().default(null),
  education: z.string().nullable().optional().default(null),
  highest_qualification: z.string().nullable().optional().default(null),
  graduation_year: z.string().nullable().optional().default(null),
  university: z.string().nullable().optional().default(null),
  certifications: z.array(z.string()).nullable().optional().default(null),
  projects: z.string().nullable().optional().default(null),
  technical_tools: z.string().nullable().optional().default(null),
  languages_known: z.string().nullable().optional().default(null),
  current_ctc: z.string().nullable().optional().default(null),
  expected_ctc: z.string().nullable().optional().default(null),
  notice_period: z.string().nullable().optional().default(null),
  willingness_to_relocate: z.string().nullable().optional().default(null),
  linkedin_url: z.string().nullable().optional().default(null),
  github_or_portfolio_url: z.string().nullable().optional().default(null),
  resume_summary: z.string().nullable().optional().default(null),
  resume_text: z.string().nullable().optional().default(null),
  ai_confidence_score: z.string().nullable().optional().default(null),
  extraction_status: z.string().nullable().optional().default(null),
});

export type CandidateParsed = z.infer<typeof candidateSchema>;
