/**
 * Phase 3 golden benchmark - curated JD cases with expected SEMANTIC properties.
 *
 * Every expectation here was written by reading the sentence and deciding what a hiring manager
 * means by it. None were generated by a model: an LLM-produced expected answer would make this
 * file a test of whether the engine agrees with a model rather than whether it reads English, and
 * the two failure modes it is supposed to catch - fabricated requirements and misread modality -
 * are exactly the ones a model would share with it.
 *
 * Cases are deliberately adversarial. Easy JDs never caught anything; the ones below are drawn
 * from the constructions that actually break keyword extractors: negation, double negation,
 * contrast clauses, modality that arrives after the subject, and the same token appearing twice at
 * two different strengths.
 */

import type { JobRecordInput } from './engine.js';
import type { RequirementLevel, Seniority } from './contract.js';

export interface GoldenCase {
  name: string;
  category: string;
  job: JobRecordInput;
  expect: {
    /** Subject must appear at exactly this level somewhere in requirements. */
    level?: { subject: string; level: RequirementLevel }[];
    /** Subject must NOT appear at this level - the anti-fabrication assertion. */
    notLevel?: { subject: string; level: RequirementLevel }[];
    /** Subject must not appear as a requirement at all. */
    absent?: string[];
    negated?: string[];
    experience?: { min?: number; max?: number | null; subject?: RegExp; type?: string }[];
    seniority?: Seniority | null;
    seniorityConfidenceNot?: string;
    capabilities?: string[];
    ambiguityTypes?: string[];
    contradictionTypes?: string[];
    context?: { subject: string; context: string }[];
    relationship?: { name: string; type: string; target: string }[];
  };
}

const jd = (title: string, description: string, extra: Partial<JobRecordInput> = {}): JobRecordInput =>
  ({ id: 1, title, description, ...extra });

// ---------------------------------------------------------------- modality
const MODALITY: GoldenCase[] = [
  { name: 'must have -> MANDATORY', category: 'modality',
    job: jd('Backend Engineer', 'You must have Python for this role.'),
    expect: { level: [{ subject: 'Python', level: 'MANDATORY' }] } },
  { name: 'is required -> MANDATORY', category: 'modality',
    job: jd('Backend Engineer', 'Python is required.'),
    expect: { level: [{ subject: 'Python', level: 'MANDATORY' }] } },
  { name: 'we require -> MANDATORY', category: 'modality',
    job: jd('Backend Engineer', 'We require Django on this team.'),
    expect: { level: [{ subject: 'Django', level: 'MANDATORY' }] } },
  { name: 'essential -> MANDATORY', category: 'modality',
    job: jd('Backend Engineer', 'Kubernetes is essential.'),
    expect: { level: [{ subject: 'Kubernetes', level: 'MANDATORY' }] } },
  { name: 'proven track record -> MANDATORY', category: 'modality',
    job: jd('Backend Engineer', 'Proven track record with Go.'),
    expect: { level: [{ subject: 'Go', level: 'MANDATORY' }] } },
  { name: 'minimum of N -> MANDATORY', category: 'modality',
    job: jd('Backend Engineer', 'Minimum of 3 years with Java.'),
    expect: { level: [{ subject: 'Java', level: 'MANDATORY' }] } },
  { name: 'strongly preferred -> STRONGLY_PREFERRED', category: 'modality',
    job: jd('Backend Engineer', 'Rust is strongly preferred.'),
    expect: { level: [{ subject: 'Rust', level: 'STRONGLY_PREFERRED' }] } },
  { name: 'highly desirable -> STRONGLY_PREFERRED', category: 'modality',
    job: jd('Backend Engineer', 'Scala is highly desirable.'),
    expect: { level: [{ subject: 'Scala', level: 'STRONGLY_PREFERRED' }] } },
  { name: 'is preferred -> PREFERRED', category: 'modality',
    job: jd('Backend Engineer', 'AWS is preferred.'),
    expect: { level: [{ subject: 'AWS', level: 'PREFERRED' }] } },
  { name: 'preferably -> PREFERRED', category: 'modality',
    job: jd('Backend Engineer', 'Preferably with Terraform.'),
    expect: { level: [{ subject: 'Terraform', level: 'PREFERRED' }] } },
  { name: 'ideally -> PREFERRED', category: 'modality',
    job: jd('Backend Engineer', 'Ideally you have used RabbitMQ.'),
    expect: { level: [{ subject: 'RabbitMQ', level: 'PREFERRED' }] } },
  { name: 'familiarity with -> PREFERRED', category: 'modality',
    job: jd('Backend Engineer', 'Familiarity with Redis.'),
    expect: { level: [{ subject: 'Redis', level: 'PREFERRED' }] } },
  { name: 'exposure to -> PREFERRED', category: 'modality',
    job: jd('Backend Engineer', 'Exposure to GraphQL.'),
    expect: { level: [{ subject: 'GraphQL', level: 'PREFERRED' }] } },
  { name: 'is a plus -> OPTIONAL', category: 'modality',
    job: jd('Backend Engineer', 'Kubernetes is a plus.'),
    expect: { level: [{ subject: 'Kubernetes', level: 'OPTIONAL' }] } },
  { name: 'nice to have -> OPTIONAL', category: 'modality',
    job: jd('Backend Engineer', 'React is nice to have.'),
    expect: { level: [{ subject: 'React', level: 'OPTIONAL' }] } },
  { name: 'bonus points -> OPTIONAL', category: 'modality',
    job: jd('Backend Engineer', 'Bonus points for Kotlin.'),
    expect: { level: [{ subject: 'Kotlin', level: 'OPTIONAL' }] } },
  { name: 'good to have -> OPTIONAL', category: 'modality',
    job: jd('Backend Engineer', 'Good to have Jenkins.'),
    expect: { level: [{ subject: 'Jenkins', level: 'OPTIONAL' }] } },
  { name: 'optional -> OPTIONAL', category: 'modality',
    job: jd('Backend Engineer', 'Angular is optional.'),
    expect: { level: [{ subject: 'Angular', level: 'OPTIONAL' }] } },
  { name: 'mention with no cue is INFORMATIONAL not MANDATORY', category: 'modality',
    job: jd('Backend Engineer', 'Our stack includes MongoDB.'),
    expect: { level: [{ subject: 'MongoDB', level: 'INFORMATIONAL' }],
      notLevel: [{ subject: 'MongoDB', level: 'MANDATORY' }] } },
  { name: 'you will build ... using -> CONTEXTUAL', category: 'modality',
    job: jd('Backend Engineer', 'You will build services using Go.'),
    expect: { level: [{ subject: 'Go', level: 'CONTEXTUAL' }],
      notLevel: [{ subject: 'Go', level: 'MANDATORY' }] } },
  { name: 'strongly preferred not swallowed by preferred', category: 'modality',
    job: jd('Backend Engineer', 'Vue.js is strongly preferred.'),
    expect: { level: [{ subject: 'Vue.js', level: 'STRONGLY_PREFERRED' }],
      notLevel: [{ subject: 'Vue.js', level: 'PREFERRED' }] } },
];

// ---------------------------------------------------------------- negation
const NEGATION: GoldenCase[] = [
  { name: 'is not required -> EXCLUDED', category: 'negation',
    job: jd('Backend Engineer', 'Python is not required.'),
    expect: { level: [{ subject: 'Python', level: 'EXCLUDED' }], negated: ['Python'],
      notLevel: [{ subject: 'Python', level: 'MANDATORY' }] } },
  { name: 'not mandatory -> EXCLUDED', category: 'negation',
    job: jd('Backend Engineer', 'Docker is not mandatory.'),
    expect: { level: [{ subject: 'Docker', level: 'EXCLUDED' }] } },
  { name: 'does not require -> EXCLUDED', category: 'negation',
    job: jd('Backend Engineer', 'This role does not require PHP.'),
    expect: { level: [{ subject: 'PHP', level: 'EXCLUDED' }] } },
  { name: 'no experience with X is required -> EXCLUDED', category: 'negation',
    job: jd('Backend Engineer', 'No experience with PHP is required.'),
    expect: { level: [{ subject: 'PHP', level: 'EXCLUDED' }] } },
  { name: 'not strictly required -> EXCLUDED', category: 'negation',
    job: jd('Backend Engineer', 'Kotlin is not strictly required.'),
    expect: { level: [{ subject: 'Kotlin', level: 'EXCLUDED' }] } },
  { name: 'double negative -> MANDATORY', category: 'negation',
    job: jd('Backend Engineer', 'Candidates without production Kubernetes experience will not be considered.'),
    expect: { level: [{ subject: 'Kubernetes', level: 'MANDATORY' }] } },
  { name: 'without ... need not apply -> MANDATORY', category: 'negation',
    job: jd('Backend Engineer', 'Applicants without Java need not apply.'),
    expect: { level: [{ subject: 'Java', level: 'MANDATORY' }] } },
  { name: 'only candidates with -> MANDATORY', category: 'negation',
    job: jd('Backend Engineer', 'Only candidates with Scala will be reviewed.'),
    expect: { level: [{ subject: 'Scala', level: 'MANDATORY' }] } },
  { name: 'negation scope does not reach earlier subject', category: 'negation',
    job: jd('Backend Engineer', 'Python is required. Kubernetes is not required.'),
    expect: { level: [{ subject: 'Python', level: 'MANDATORY' }, { subject: 'Kubernetes', level: 'EXCLUDED' }] } },
  { name: 'excluded requirement demands no evidence', category: 'negation',
    job: jd('Backend Engineer', 'Ruby is not required.'),
    expect: { level: [{ subject: 'Ruby', level: 'EXCLUDED' }] } },
];

// ---------------------------------------------------------------- experience
const EXPERIENCE: GoldenCase[] = [
  { name: '5+ years bound to its subject', category: 'experience',
    job: jd('Backend Engineer', 'We require 5+ years of backend engineering.'),
    expect: { experience: [{ min: 5, max: null, subject: /backend/i }] } },
  { name: '3+ years AT_LEAST', category: 'experience',
    job: jd('Backend Engineer', '3+ years of Python development required.'),
    expect: { experience: [{ min: 3, max: null }] } },
  { name: '2-4 years RANGE', category: 'experience',
    job: jd('Backend Engineer', 'Looking for 2-4 years of experience in Java.'),
    expect: { experience: [{ min: 2, max: 4 }] } },
  { name: '3 to 5 years RANGE', category: 'experience',
    job: jd('Backend Engineer', 'We need 3 to 5 years of Go.'),
    expect: { experience: [{ min: 3, max: 5 }] } },
  { name: 'exact years', category: 'experience',
    job: jd('Backend Engineer', 'Requires 5 years of Django.'),
    expect: { experience: [{ min: 5, max: 5 }] } },
  { name: 'months convert to years', category: 'experience',
    job: jd('Backend Engineer', 'At least 18 months of Node.js.'),
    expect: { experience: [{ min: 1.5 }] } },
  { name: 'production experience typed', category: 'experience',
    job: jd('SRE', 'Must have 4+ years of production Kubernetes experience.'),
    expect: { experience: [{ min: 4, type: 'PRODUCTION' }] } },
  { name: 'hands-on experience typed', category: 'experience',
    job: jd('Backend Engineer', '3+ years hands-on experience with Spring.'),
    expect: { experience: [{ min: 3, type: 'HANDS_ON' }] } },
  { name: 'leadership experience typed', category: 'experience',
    job: jd('Engineering Manager', '5+ years leading engineering teams.'),
    expect: { experience: [{ min: 5, type: 'LEADERSHIP' }] } },
  { name: 'recent experience typed', category: 'experience',
    job: jd('Backend Engineer', '2+ years of recent Python work.'),
    expect: { experience: [{ min: 2, type: 'RECENT' }] } },
  { name: 'unquantified senior-level experience recorded as ambiguous', category: 'experience',
    job: jd('Backend Engineer', 'Senior-level experience expected.'),
    expect: { experience: [{ min: undefined }] } },
];

// ---------------------------------------------------------------- seniority
const SENIORITY: GoldenCase[] = [
  { name: 'senior from title', category: 'seniority',
    job: jd('Senior Backend Engineer', 'Must have 6+ years of Python.'),
    expect: { seniority: 'SENIOR' } },
  { name: 'junior from title', category: 'seniority',
    job: jd('Junior Developer', 'Entry level role with 1 year of Java.'),
    expect: { seniority: 'JUNIOR' } },
  { name: 'staff from title', category: 'seniority',
    job: jd('Staff Engineer', 'Own technical direction across multiple teams. 9+ years required.'),
    expect: { seniority: 'STAFF' } },
  { name: 'principal from title', category: 'seniority',
    job: jd('Principal Engineer', 'Owns the architecture for the platform. 10+ years.'),
    expect: { seniority: 'PRINCIPAL' } },
  { name: 'architect from title', category: 'seniority',
    job: jd('Solutions Architect', 'Design enterprise systems. 10 years required.'),
    expect: { seniority: 'ARCHITECT' } },
  { name: 'manager from title', category: 'seniority',
    job: jd('Engineering Manager', 'Managing a team of engineers. 7+ years.'),
    expect: { seniority: 'MANAGER' } },
  { name: 'director from title', category: 'seniority',
    job: jd('Director of Engineering', 'Setting technical strategy. 12 years.'),
    expect: { seniority: 'DIRECTOR' } },
  { name: 'intern from title', category: 'seniority',
    job: jd('Software Engineering Intern', 'Work with guidance on small features.'),
    expect: { seniority: 'INTERN' } },
  { name: 'seniority never taken from title alone when signals conflict', category: 'seniority',
    job: jd('Senior Backend Engineer', 'This role requires 1-2 years of experience.'),
    expect: { seniority: 'SENIOR', seniorityConfidenceNot: 'EXPLICIT',
      contradictionTypes: ['SENIORITY_VS_EXPERIENCE'] } },
  { name: 'no seniority signal -> null/UNRESOLVED', category: 'seniority',
    job: jd('Engineer', 'Work on our product.'),
    expect: { seniority: null } },
];

// ---------------------------------------------------------------- context
const CONTEXT: GoldenCase[] = [
  { name: 'Python scripting context preserved', category: 'context',
    job: jd('Analyst', 'Python scripting is required for automation tasks.'),
    expect: { context: [{ subject: 'Python', context: 'scripting' }] } },
  { name: 'SQL reporting context preserved', category: 'context',
    job: jd('Analyst', 'SQL reporting is required.'),
    expect: { context: [{ subject: 'SQL', context: 'reporting' }] } },
  { name: 'production context preserved', category: 'context',
    job: jd('SRE', 'Kubernetes in production is required.'),
    expect: { context: [{ subject: 'Kubernetes', context: 'production' }] } },
  // React Native must resolve to its OWN canonical entry, not be folded into React. Conflating
  // them would tell a later phase that a web React developer satisfies a mobile requirement.
  { name: 'React Native is not conflated with React', category: 'context',
    job: jd('Mobile Engineer', 'React Native mobile development is required.'),
    expect: { context: [{ subject: 'React Native', context: 'mobile' }],
      absent: ['React'] } },
  { name: 'dashboard context preserved', category: 'context',
    job: jd('Frontend Engineer', 'React dashboards are required.'),
    expect: { context: [{ subject: 'React', context: 'dashboard' }] } },
  { name: 'architecture context preserved', category: 'context',
    job: jd('Architect', 'PostgreSQL architecture experience is required.'),
    expect: { context: [{ subject: 'PostgreSQL', context: 'architecture' }] } },
];

// ---------------------------------------------------------------- capability
const CAPABILITY: GoldenCase[] = [
  { name: 'distributed service design -> capabilities', category: 'capability',
    job: jd('Backend Engineer', 'Design and maintain scalable distributed services.'),
    expect: { capabilities: ['service design', 'distributed systems', 'backend architecture', 'scalability engineering'] } },
  { name: 'REST API -> API capabilities', category: 'capability',
    job: jd('Backend Engineer', 'Build scalable REST APIs.'),
    expect: { capabilities: ['API design', 'API implementation'] } },
  { name: 'cloud deployment capability', category: 'capability',
    job: jd('Backend Engineer', 'Deploy services on AWS.'),
    expect: { capabilities: ['cloud deployment'] } },
  { name: 'container orchestration capability', category: 'capability',
    job: jd('SRE', 'Operate Kubernetes clusters.'),
    expect: { capabilities: ['container orchestration'] } },
  { name: 'CI/CD capability', category: 'capability',
    job: jd('DevOps Engineer', 'Design CI/CD pipelines.'),
    expect: { capabilities: ['build and release engineering'] } },
  { name: 'production engineering capability from on-call', category: 'capability',
    job: jd('SRE', 'Participate in on-call and incident response.'),
    expect: { capabilities: ['production engineering'] } },
  { name: 'data engineering capability', category: 'capability',
    job: jd('Data Engineer', 'Build ETL data pipelines.'),
    expect: { capabilities: ['data engineering'] } },
  { name: 'mentorship capability', category: 'capability',
    job: jd('Senior Engineer', 'Mentor junior engineers.'),
    expect: { capabilities: ['technical mentorship'] } },
];

// ---------------------------------------------------------------- ambiguity
const AMBIGUITY: GoldenCase[] = [
  { name: 'unspecified cloud platform', category: 'ambiguity',
    job: jd('Engineer', 'Experience with cloud platforms is required.'),
    expect: { ambiguityTypes: ['UNSPECIFIED_TECHNOLOGY'] } },
  { name: 'unspecified databases', category: 'ambiguity',
    job: jd('Engineer', 'Experience with databases is required.'),
    expect: { ambiguityTypes: ['UNSPECIFIED_TECHNOLOGY'] } },
  { name: 'unspecified programming languages', category: 'ambiguity',
    job: jd('Engineer', 'Experience with programming languages is required.'),
    expect: { ambiguityTypes: ['UNSPECIFIED_TECHNOLOGY'] } },
  { name: 'vague qualifier strong knowledge', category: 'ambiguity',
    job: jd('Engineer', 'Strong knowledge of algorithms is required.'),
    expect: { ambiguityTypes: ['VAGUE_QUALIFIER'] } },
  { name: 'vague qualifier solid understanding', category: 'ambiguity',
    job: jd('Engineer', 'Solid understanding of systems is required.'),
    expect: { ambiguityTypes: ['VAGUE_QUALIFIER'] } },
  { name: 'named technology is not ambiguous', category: 'ambiguity',
    job: jd('Engineer', 'AWS is required.'),
    expect: { ambiguityTypes: [] } },
];

// ---------------------------------------------------------------- contradiction
const CONTRADICTION: GoldenCase[] = [
  { name: 'senior title vs 1-2 years', category: 'contradiction',
    job: jd('Senior Backend Engineer', 'Requires 1-2 years of experience.'),
    expect: { contradictionTypes: ['SENIORITY_VS_EXPERIENCE'] } },
  { name: 'principal title vs 2 years', category: 'contradiction',
    job: jd('Principal Engineer', 'Requires 2 years of experience.'),
    expect: { contradictionTypes: ['SENIORITY_VS_EXPERIENCE'] } },
  { name: 'consistent senior JD has no seniority contradiction', category: 'contradiction',
    job: jd('Senior Backend Engineer', 'Requires 7+ years of experience.'),
    expect: { contradictionTypes: [] } },
];

// ---------------------------------------------------------------- noise
const NOISE: GoldenCase[] = [
  { name: 'HTML contamination', category: 'noise',
    job: jd('Backend Engineer', '<p><strong>Python</strong> is required.</p>'),
    expect: { level: [{ subject: 'Python', level: 'MANDATORY' }] } },
  { name: 'markdown contamination', category: 'noise',
    job: jd('Backend Engineer', '- **Python** is required\n- Go is a plus'),
    expect: { level: [{ subject: 'Python', level: 'MANDATORY' }, { subject: 'Go', level: 'OPTIONAL' }] } },
  { name: 'CRLF and whitespace noise', category: 'noise',
    job: jd('Backend Engineer', 'Python   is    required.\r\n\r\n'),
    expect: { level: [{ subject: 'Python', level: 'MANDATORY' }] } },
  { name: 'alias resolves to canonical - K8s', category: 'noise',
    job: jd('SRE', 'K8s is required.'),
    expect: { level: [{ subject: 'Kubernetes', level: 'MANDATORY' }] } },
  { name: 'alias resolves to canonical - NodeJS', category: 'noise',
    job: jd('Backend Engineer', 'NodeJS is required.'),
    expect: { level: [{ subject: 'Node.js', level: 'MANDATORY' }] } },
  { name: 'alias resolves to canonical - JS', category: 'noise',
    job: jd('Frontend Engineer', 'JS is required.'),
    expect: { level: [{ subject: 'JavaScript', level: 'MANDATORY' }] } },
  { name: 'alias resolves to canonical - ReactJS', category: 'noise',
    job: jd('Frontend Engineer', 'ReactJS is required.'),
    expect: { level: [{ subject: 'React', level: 'MANDATORY' }] } },
  { name: 'alias resolves to canonical - Golang', category: 'noise',
    job: jd('Backend Engineer', 'Golang is required.'),
    expect: { level: [{ subject: 'Go', level: 'MANDATORY' }] } },
  { name: 'empty description yields no requirements', category: 'noise',
    job: jd('Engineer', ''),
    expect: { absent: ['Python', 'Java', 'Go'] } },
  { name: 'unrelated prose invents nothing', category: 'noise',
    job: jd('Engineer', 'We are a fast growing company with a great culture and free lunch.'),
    expect: { absent: ['Python', 'Java', 'AWS', 'Kubernetes'] } },
];

// ---------------------------------------------------------------- relationships
const RELATIONSHIPS: GoldenCase[] = [
  { name: 'FastAPI IS_A backend framework', category: 'relationship',
    job: jd('Backend Engineer', 'FastAPI is required.'),
    expect: { relationship: [{ name: 'FastAPI', type: 'IS_A', target: 'backend framework' }] } },
  { name: 'FastAPI USED_FOR API development', category: 'relationship',
    job: jd('Backend Engineer', 'FastAPI is required.'),
    expect: { relationship: [{ name: 'FastAPI', type: 'USED_FOR', target: 'API development' }] } },
  { name: 'PostgreSQL IS_A data store', category: 'relationship',
    job: jd('Backend Engineer', 'PostgreSQL is required.'),
    expect: { relationship: [{ name: 'PostgreSQL', type: 'IS_A', target: 'data store' }] } },
  { name: 'Kubernetes USED_FOR deployment automation', category: 'relationship',
    job: jd('SRE', 'Kubernetes is required.'),
    expect: { relationship: [{ name: 'Kubernetes', type: 'USED_FOR', target: 'deployment automation' }] } },
  { name: 'AWS IS_A cloud platform', category: 'relationship',
    job: jd('SRE', 'AWS is required.'),
    expect: { relationship: [{ name: 'AWS', type: 'IS_A', target: 'cloud platform' }] } },
];

// ---------------------------------------------------------------- realistic composites
const COMPOSITE: GoldenCase[] = [
  { name: 'brief example JD - full understanding', category: 'composite',
    job: jd('Backend Engineer',
      'Build scalable REST APIs using Python and FastAPI, deploy services using AWS and Kubernetes.'),
    expect: {
      level: [{ subject: 'Python', level: 'CONTEXTUAL' }, { subject: 'FastAPI', level: 'CONTEXTUAL' }],
      capabilities: ['API design', 'API implementation', 'cloud deployment', 'container orchestration'],
      relationship: [{ name: 'FastAPI', type: 'USED_FOR', target: 'API development' }],
    } },
  { name: 'mixed modality in one JD', category: 'composite',
    job: jd('Senior Backend Engineer',
      'Python is required. AWS is preferred. Kubernetes is a plus. PHP is not required.',
      { required_skills: ['Python'], optional_skills: ['Redis'] }),
    expect: {
      level: [
        { subject: 'Python', level: 'MANDATORY' },
        { subject: 'AWS', level: 'PREFERRED' },
        { subject: 'Kubernetes', level: 'OPTIONAL' },
        { subject: 'PHP', level: 'EXCLUDED' },
        { subject: 'Redis', level: 'PREFERRED' },
      ],
    } },
  { name: 'structured columns supply their own strength', category: 'composite',
    job: jd('Backend Engineer', 'A general description.',
      { required_skills: ['Python', 'Go'], optional_skills: ['Rust'] }),
    expect: {
      level: [{ subject: 'Python', level: 'MANDATORY' }, { subject: 'Go', level: 'MANDATORY' },
        { subject: 'Rust', level: 'PREFERRED' }],
    } },
  { name: 'senior SRE realistic posting', category: 'composite',
    job: jd('Senior Site Reliability Engineer',
      'You will operate Kubernetes clusters in production and participate in on-call. '
      + 'Must have 5+ years of production experience. Terraform is strongly preferred. '
      + 'Experience with cloud platforms is required.',
      { required_skills: ['Kubernetes'], location: 'Bengaluru', employment_type: 'Full-time' }),
    expect: {
      seniority: 'SENIOR',
      level: [{ subject: 'Kubernetes', level: 'MANDATORY' }, { subject: 'Terraform', level: 'STRONGLY_PREFERRED' }],
      capabilities: ['container orchestration', 'production engineering'],
      ambiguityTypes: ['UNSPECIFIED_TECHNOLOGY'],
      experience: [{ min: 5, type: 'PRODUCTION' }],
    } },
  { name: 'data role realistic posting', category: 'composite',
    job: jd('Data Engineer',
      'Build ETL data pipelines. 3+ years of Python required. MongoDB is nice to have.',
      { required_skills: ['Python', 'SQL'] }),
    expect: {
      level: [{ subject: 'Python', level: 'MANDATORY' }, { subject: 'MongoDB', level: 'OPTIONAL' }],
      capabilities: ['data engineering'],
      experience: [{ min: 3 }],
    } },
];

// ---------------------------------------------------------------- structural edge cases
const EDGE: GoldenCase[] = [
  { name: 'duplicate skill mentioned twice at two strengths keeps both readings', category: 'edge',
    job: jd('Backend Engineer', 'Python is required. Python is also a plus for scripting work.'),
    expect: { level: [{ subject: 'Python', level: 'MANDATORY' }, { subject: 'Python', level: 'OPTIONAL' }] } },
  { name: 'duplicate identical skill in a structured column is deduplicated', category: 'edge',
    job: jd('Backend Engineer', 'A role.', { required_skills: ['Python', 'python', 'PYTHON'] }),
    expect: { level: [{ subject: 'Python', level: 'MANDATORY' }] } },
  { name: 'cross-field disagreement is preserved, not silently reconciled', category: 'edge',
    job: jd('Backend Engineer', 'Redis is a plus.', { required_skills: ['Redis'] }),
    expect: { level: [{ subject: 'Redis', level: 'MANDATORY' }, { subject: 'Redis', level: 'OPTIONAL' }] } },
  { name: 'PDF extraction noise - broken spacing and hyphenation', category: 'edge',
    job: jd('Backend Engineer', 'Py t h o n\n\n\nDocker   is    required .'),
    expect: { level: [{ subject: 'Docker', level: 'MANDATORY' }], absent: ['Python'] } },
  { name: 'nested responsibilities in one sentence', category: 'edge',
    job: jd('Backend Engineer', 'You will design distributed services, build REST APIs and deploy on AWS.'),
    expect: { capabilities: ['service design', 'API design', 'cloud deployment'] } },
  { name: 'multiple roles in one posting', category: 'edge',
    job: jd('Backend Engineer / DevOps Engineer', 'Python is required. Terraform is required.'),
    expect: { level: [{ subject: 'Python', level: 'MANDATORY' }, { subject: 'Terraform', level: 'MANDATORY' }] } },
  { name: 'employment and location constraints captured', category: 'edge',
    job: jd('Backend Engineer', 'A role.',
      { location: 'Bengaluru', employment_type: 'Full-time', remote_type: 'hybrid' }),
    expect: { level: [{ subject: 'Bengaluru', level: 'MANDATORY' }, { subject: 'hybrid', level: 'MANDATORY' }] } },
  { name: 'education and certification columns are mandatory requirements', category: 'edge',
    job: jd('Backend Engineer', 'A role.',
      { education: ['B.Tech'], certifications: ['AWS Certified Solutions Architect'] }),
    expect: { level: [{ subject: 'B.Tech', level: 'MANDATORY' }] } },
  { name: 'years with no subject is recorded but subject stays null', category: 'edge',
    job: jd('Backend Engineer', 'We need 5+ years.'),
    expect: { experience: [{ min: 5 }] } },
  { name: 'not necessarily required -> EXCLUDED', category: 'edge',
    job: jd('Backend Engineer', 'Docker is not necessarily required.'),
    expect: { level: [{ subject: 'Docker', level: 'EXCLUDED' }] } },
  { name: 'dotted technology name keeps its modality (Node.js)', category: 'edge',
    job: jd('Backend Engineer', 'Node.js is required.'),
    expect: { level: [{ subject: 'Node.js', level: 'MANDATORY' }],
      notLevel: [{ subject: 'JavaScript', level: 'MANDATORY' }] } },
  { name: 'dotted name does not fabricate a JavaScript requirement', category: 'edge',
    job: jd('Frontend Engineer', 'Vue.js is a plus.'),
    expect: { level: [{ subject: 'Vue.js', level: 'OPTIONAL' }], absent: ['JavaScript'] } },
  { name: 'decimal years survive sentence splitting', category: 'edge',
    job: jd('Backend Engineer', 'We require 2.5 years of Python.'),
    expect: { experience: [{ min: 2.5 }], level: [{ subject: 'Python', level: 'MANDATORY' }] } },
  { name: 'abbreviation resolves - CI/CD tooling', category: 'edge',
    job: jd('DevOps Engineer', 'Experience with CI/CD tools is required.'),
    expect: { ambiguityTypes: ['UNSPECIFIED_TECHNOLOGY'] } },
  { name: 'empty title yields no seniority and no role family', category: 'edge',
    job: { id: 1, title: null, description: 'Python is required.' },
    expect: { seniority: null, level: [{ subject: 'Python', level: 'MANDATORY' }] } },
];

export const GOLDEN_CASES: GoldenCase[] = [
  ...MODALITY, ...NEGATION, ...EXPERIENCE, ...SENIORITY, ...CONTEXT,
  ...CAPABILITY, ...AMBIGUITY, ...CONTRADICTION, ...NOISE, ...RELATIONSHIPS,
  ...COMPOSITE, ...EDGE,
];

/**
 * Fabrication probes: JDs that mention NOTHING requiring these technologies. Any requirement the
 * engine emits for them is a false inference, and the false-inference rate is computed directly
 * from this set rather than estimated.
 */
export const FALSE_INFERENCE_PROBES: { job: JobRecordInput; mustNotContain: string[] }[] = [
  { job: jd('Engineer', 'We value collaboration and clear communication.'),
    mustNotContain: ['Python', 'Java', 'AWS', 'Kubernetes', 'React', 'PostgreSQL'] },
  { job: jd('Engineer', 'Competitive salary, flexible hours, and a hybrid working model.'),
    mustNotContain: ['Python', 'Docker', 'MySQL', 'Go'] },
  { job: jd('Recruiter', 'Source and screen candidates for engineering roles.'),
    mustNotContain: ['Python', 'Kubernetes', 'Terraform'] },
  { job: jd('Engineer', 'Our office has a coffee machine and a table tennis table.'),
    mustNotContain: ['Java', 'Spring', 'AWS'] },
  { job: jd('Engineer', 'This is a 6 month contract role based in Pune.'),
    mustNotContain: ['Python', 'React', 'Angular'] },
];
